# Generated by Django 3.1.3 on 2021-02-10 20:35

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('minos', '0009_delete_comptable'),
    ]

    operations = [
        migrations.AddField(
            model_name='ulttoken',
            name='token_bank_number2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ulttoken',
            name='validated',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='ulttoken',
            name='amount_paid_ult',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ulttoken',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='ulttoken',
            name='motif',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='ulttoken',
            name='student',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ulttoken',
            name='token_bank_number',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tokenbank', to='minos.banktoken'),
        ),
    ]
